package com.kylin.webapp.servlet.redirect;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.Enumeration;

import javax.inject.Inject;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.kylin.webapp.WebAppService;

/**
 * http://localhost:8080/webapp/HTTPHeaderServlet?name=qweqeqeqweqweqeqeqweqweqweqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqeqeqweqqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqwqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqeqeqeqweqweqeqeqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqwasdadsaaaaaaaaaaaaaaaaaaaaawaseqeqeqweqeqeqeqweqwasdadsaaaaaaaaaaaaaaaaaaaaawassdadsaaaaaaaaaaaaaaaaaaaaawasqeqeqeqweqwasdadsaaaaaaaaaaaaaaaaaaaaawasdadsaaaaaaaaaaaaaaaaaaaaaaaasdadadqweqeqeqweqweqeqeqweqweqweqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqeqeqweqqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqwqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqeqeqeqweqweqeqeqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqweqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqeqeqweqweqeqeqweqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqqeqeqeqweqwaqwqweqeqeqweqeqeqeqweqwasdadsaaaaaaaaaaaaaaaaaaaaawaseqeqeqweqeqeqeqweqwasdadsaaaaaaaaaaaaaaaaaaaaawassdadsaaaaaaaaaaaaaaaaaaaaawasqeqeqeqweqwasdadsaaaaaaaaaaaaaaaaaaaaawasdadsaaaaaaaaaaaaaaaaaaaaaaaasdadadsadsasdfsdfsfsfsfsfsfsdfsfssadsasdfsdfsfsfsfsfsfsdfsfs
 * 
 * @author kylin
 *
 */

@WebServlet("/HTTPHeaderServlet")
public class HTTPHeaderServlet extends HttpServlet{

	private static final long serialVersionUID = -5718021812757448305L;
	
	@Inject
	private WebAppService service;

	protected void doGet(HttpServletRequest req, HttpServletResponse resp)throws ServletException, IOException {
		
		resp.setContentType(service.contentType());
		
		PrintWriter out = resp.getWriter();
		
		out.println(service.pageHeader("Http Header Test Example"));
		out.println("<h3>Http Header Test Example</h3>");
		
		out.println("Print All HeaderContent" + "<br>");
		out.println("<br>");
		
		Enumeration<String> en = req.getHeaderNames();
		while(en.hasMoreElements()) {
			String content = en.nextElement();
			out.println(content);
			out.println("<br>");
		}
		
		out.println("<br>");
		out.println("Param value : " + req.getParameter("name"));
		out.println("<br>");
		out.println("<br>");
		out.println("Param length: " + req.getParameter("name").length());
		out.close();
	}

	protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
		doGet(req, resp);
	}

}
