SSL configuration on EAP 5
--------------------------

* Generate a new SSL certificate using the *keytool* application.
The full command will be:
----
keytool -genkey -alias jboss -keyalg RSA -keystore test.keystore -validity 3650
----
Set the password for the keystore and key to be `password`


You may set the other values to anything you like for the purposes of this lab. Hint: Generally, the first and last name entry is set to the hostname of your server (localhost in this case), to avoid some security warnings in the broswer. Remember what they are, so you can confirm them against the output from the browser in the last step.

* Enable https in JBoss [deploy/jbossweb.sar] (port 8443) in the server.xml file, using the certificate generated in the previous step by editing the keystoreFile and keystorePass in the SSL connector.
The keystorePass should be `password`, and the keystoreFile can be referred to via ${jboss.server.home.dir}/test.keystore


Edit the server.xml file in jboss-eap-5.0/jboss-as/server/$PROFILE/deploy/jbossweb.sar directory. Add & configure https connector as below;


<Connector protocol="HTTP/1.1" SSLEnabled="true" 
           port="8443" address="${jboss.bind.address}"
           scheme="https" secure="true" clientAuth="false" 
           keystoreFile="${jboss.server.home.dir}/test.keystore"
           keystorePass="redhat" sslProtocol = "TLS" />


* Restart JBoss & test
Test SSL configuration from https://localhost:8443






